/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 2.0.0
 * Contact: support@instaclustr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cassandra_sidecar

type NodeTopology struct {
	// hostname of Cassandra node
	Hostname string `json:"hostname,omitempty"`
	// name of a cluster this node belongs to
	Cluster string `json:"cluster,omitempty"`
	// name of a data center this node belongs to
	Dc string `json:"dc,omitempty"`
	// name of a rack this node belongs to
	Rack string `json:"rack,omitempty"`
	// Cassandra host id of this node
	NodeId string `json:"nodeId,omitempty"`
	// IP address of a node
	IpAddress string `json:"ipAddress,omitempty"`
}
