/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 2.0.0
 * Contact: support@instaclustr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cassandra_sidecar

type ClusterTopology struct {
	// Timestamp this topology was created at
	Timestamp float64 `json:"timestamp,omitempty"`
	// name of a cluster
	ClusterName string `json:"clusterName,omitempty"`
	// Database schema version of given cluster
	SchemaVersion string `json:"schemaVersion,omitempty"`
	Topology []NodeTopology `json:"topology,omitempty"`
}
