/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 2.0.0
 * Contact: support@instaclustr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cassandra_sidecar

// triggers the immediate cleanup of keys no longer belonging to a node. By default, clean all keyspaces. 
type CleanupOperationRequest struct {
	Type_ string `json:"type"`
	// keyspace to cleanup 
	Keyspace string `json:"keyspace"`
	// tables to cleanup, when not specified, all tables in a keyspace will be cleaned up 
	Tables []string `json:"tables,omitempty"`
	// number of jobs to use, never uses more that concurrent_compactor threads 
	Jobs int32 `json:"jobs,omitempty"`
}
