/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 2.0.0
 * Contact: support@instaclustr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cassandra_sidecar
import (
	"time"
)

type SidecarVersion struct {
	// textual representation of Sidecar version
	Version string `json:"version,omitempty"`
	// timestamp this Sidecar was built
	BuildTime time.Time `json:"buildTime,omitempty"`
	// git commit hash this Sidecar was built from
	GitCommit string `json:"gitCommit,omitempty"`
}
