/*
 * Instaclustr Icarus
 *
 * REST API for Instaclustr Icarus - a sidecar for Cassandra
 *
 * API version: 1.0.2
 * Contact: support@instaclustr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package instaclustr_icarus

type ProxySettings struct {
	// if specified, it will use proxy client configuration relevant for S3 only.
	UseProxy string `json:"useProxy,omitempty"`
	// host for proxy, relevant for S3 only
	ProxyHost string `json:"proxyHost,omitempty"`
	// port for proxy, relevant for S3 only
	ProxyPort string `json:"proxyPort,omitempty"`
	// username for proxy, relevant for S3 only
	ProxyUsername string `json:"proxyUsername,omitempty"`
	// password for proxy, relevant for S3 only
	ProxyPassword string `json:"proxyPassword,omitempty"`
	// protocol for proxy, defaults to HTTPS, might be HTTP or HTTPS
	ProxyProtocol string `json:"proxyProtocol,omitempty"`
}
