/*
 * Instaclustr Icarus
 *
 * REST API for Instaclustr Icarus - a sidecar for Cassandra
 *
 * API version: 1.0.2
 * Contact: support@instaclustr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package instaclustr_icarus

type Stacktrace struct {
	MethodName string `json:"methodName,omitempty"`
	FileName string `json:"fileName,omitempty"`
	LineNumber string `json:"lineNumber,omitempty"`
	ClassName string `json:"className,omitempty"`
	NativeMethod bool `json:"nativeMethod,omitempty"`
}
