/*
 * Instaclustr Icarus
 *
 * REST API for Instaclustr Icarus - a sidecar for Cassandra
 *
 * API version: 1.0.1
 * Contact: support@instaclustr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package instaclustr_icarus

// refreshes a table, this is done by calling StorageServiceMBean#loadNewSSTables 
type RefreshOperationRequest struct {
	Type_ string `json:"type"`
	// keyspace to refresh 
	Keyspace string `json:"keyspace"`
	// table to refresh 
	Table string `json:"table"`
}
